language: ruby
script: bundle exec rake test

rvm:
  - 1.9.3
  - 2.1.2

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.0-stable
  - gemfiles/Gemfile.rails-3.2-stable
  - gemfiles/Gemfile.rails-head

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-head
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-head

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=1
    - CODECLIMATE_REPO_TOKEN=13f6e67dc6be3f749e752a3231502a48ae5e2986a557375da4339fd556031358
